#!/usr/bin/env python3
# ============================================================================
#  gen_tables.py — build-time tables (stdout -> build/tables.inc).
#
#    sin_table  signed sine, one full turn in 256 steps, amplitude 127.
#               Page aligned, so a lookup is "ld l,angle / ld h,page".
#               cos(a) = sin[(a + 64) AND 255].
#    font5x7    36 glyphs (0-9, A-Z) plus a few marks, 7 bytes each, one
#               per row, bit 4 = leftmost pixel. Used by the status strip
#               and the between-level banners.
#    strings    the handful of words the game says, as glyph indices.
# ============================================================================
import math
import os
import sys

outdir = sys.argv[1] if len(sys.argv) > 1 else "build"

print("; AUTO-GENERATED by tools/gen_tables.py — do not edit, do not commit")

# ---------------------------------------------------------------------------
FONT = {
    '0': "01110 10001 10011 10101 11001 10001 01110",
    '1': "00100 01100 00100 00100 00100 00100 01110",
    '2': "01110 10001 00001 00110 01000 10000 11111",
    '3': "11111 00010 00100 00010 00001 10001 01110",
    '4': "00010 00110 01010 10010 11111 00010 00010",
    '5': "11111 10000 11110 00001 00001 10001 01110",
    '6': "00110 01000 10000 11110 10001 10001 01110",
    '7': "11111 00001 00010 00100 01000 01000 01000",
    '8': "01110 10001 10001 01110 10001 10001 01110",
    '9': "01110 10001 10001 01111 00001 00010 01100",
    'A': "01110 10001 10001 11111 10001 10001 10001",
    'B': "11110 10001 11110 10001 10001 10001 11110",
    'C': "01110 10001 10000 10000 10000 10001 01110",
    'D': "11100 10010 10001 10001 10001 10010 11100",
    'E': "11111 10000 11110 10000 10000 10000 11111",
    'F': "11111 10000 11110 10000 10000 10000 10000",
    'G': "01110 10001 10000 10111 10001 10001 01111",
    'H': "10001 10001 11111 10001 10001 10001 10001",
    'I': "01110 00100 00100 00100 00100 00100 01110",
    'J': "00111 00010 00010 00010 00010 10010 01100",
    'K': "10001 10010 10100 11000 10100 10010 10001",
    'L': "10000 10000 10000 10000 10000 10000 11111",
    'M': "10001 11011 10101 10101 10001 10001 10001",
    'N': "10001 11001 10101 10011 10001 10001 10001",
    'O': "01110 10001 10001 10001 10001 10001 01110",
    'P': "11110 10001 10001 11110 10000 10000 10000",
    'Q': "01110 10001 10001 10001 10101 10010 01101",
    'R': "11110 10001 10001 11110 10100 10010 10001",
    'S': "01111 10000 10000 01110 00001 00001 11110",
    'T': "11111 00100 00100 00100 00100 00100 00100",
    'U': "10001 10001 10001 10001 10001 10001 01110",
    'V': "10001 10001 10001 10001 10001 01010 00100",
    'W': "10001 10001 10001 10101 10101 10101 01010",
    'X': "10001 01010 00100 00100 01010 10001 10001",
    'Y': "10001 10001 01010 00100 00100 00100 00100",
    'Z': "11111 00001 00010 00100 01000 10000 11111",
    '-': "00000 00000 00000 01110 00000 00000 00000",
    '!': "00100 00100 00100 00100 00100 00000 00100",
    ':': "00000 00100 00000 00000 00100 00000 00000",
}
ORDER = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-!:"
GLNAME = {'-': 'GL_DASH', '!': 'GL_BANG', ':': 'GL_COLON'}

for i, ch in enumerate(ORDER):
    print("%-10s equ %d" % (GLNAME.get(ch, "GL_%s" % ch), i))
print("%-10s equ %d" % ("GL_SPACE", 0xFE))
print("%-10s equ %d" % ("GL_END", 0xFF))
print("%-10s equ %d" % ("FONT_W", 5))
print("%-10s equ %d" % ("FONT_H", 7))

#  The font goes out as a binary too, for the same reason as the sine: it
#  is never written to, and the code bank has better uses for 273 bytes.
font = bytearray()
for ch in ORDER:
    rows = FONT[ch].split()
    assert len(rows) == 7 and all(len(r) == 5 for r in rows), ch
    font += bytes(int(r, 2) for r in rows)
open(os.path.join(outdir, "font.raw"), "wb").write(font)

# ---------------------------------------------------------------------------
STRINGS = [
    ("str_level",   "LEVEL"),
    ("str_clear",   "FORT DOWN!"),
    ("str_fail",    "OUT OF BIRDS"),
    ("str_retry",   "SPACE - RETRY"),
    ("str_next",    "SPACE - NEXT"),
    ("str_birds",   "BIRDS"),
    ("str_furious", "FURIOUS"),
    ("str_fowland", "FOWL AND"),
    ("str_start",   "SPACE TO START"),
    ("str_thfowl",  "UP - THROW FOWLS"),
    ("str_thpig",   "UP - THROW PIGS"),
    ("str_credit",  "REVIVE8BIT - 2026 - VASPER"),
    ("str_pigs",    "PIGS"),
]


def enc(txt):
    return ",".join("#FE" if c == ' ' else str(ORDER.index(c))
                    for c in txt) + ",#FF"


for name, txt in STRINGS:
    print("%s:" % name)
    print("        db      %s" % enc(txt))

# ---------------------------------------------------------------------------
#  The sine goes out as a BINARY, not as source. It has to be page aligned
#  for the "ld h,table/256" lookup, so in the code bank it cost 256 bytes
#  plus up to 255 more of padding to reach the page — half a kilobyte of a
#  sixteen-kilobyte budget, for a table that is never written to. It rides
#  down from video RAM with the creature art instead. See art.asm.
SIN = [round(127 * math.sin(i * 2 * math.pi / 256)) for i in range(256)]
assert SIN[0] == 0 and SIN[64] == 127 and SIN[192] == -127
open(os.path.join(outdir, "sin.raw"), "wb").write(bytes(v & 0xFF for v in SIN))
