#!/usr/bin/env python3
# ============================================================================
#  gen_art.py — IMPORT the spritesheets into the build.
#
#      python3 tools/gen_art.py            (run for you by `make`)
#
#  Reads assets/sheets/*.png and writes, into build/:
#
#    creatures.raw   54 frames x 256 B, nibble packed, straight bitmaps.
#                    Staged into video RAM by the loader and copied down
#                    to #0300 at boot — the blitter needs random access.
#    blocks.raw      50 pieces x 128 B, nibble packed. Lives at #8000.
#    scenery.raw     the twelve 32x64 cells, RLE'd COLUMN-WISE (see below).
#    art_defs.inc    the equates the assembler needs to address all of it.
#
#  WHY SCENERY IS COMPRESSED, AND WHY LIKE THAT
#  --------------------------------------------
#  Twelve 32x64 cells is 12 KB raw and there is no 12 KB left: creature
#  frames and block pieces have already claimed low RAM and the #8000
#  bank. But scenery is only ever drawn by the column renderer, which
#  walks ONE 4-pixel-wide strip from top to bottom at a time — so it can
#  read a run-length stream directly, with no buffer and no decompression
#  step. Each cell becomes 8 independent strips of (count, byte, byte)
#  runs, indexed by a small offset table. Big flat skies and canopies
#  collapse to almost nothing, and the renderer gets FASTER, not slower,
#  because a 40-row run of sky is one loop iteration instead of forty.
# ============================================================================
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import artlib
from sheetdefs import (SHEETS, CREATURE_NAMES, CREATURE_FRAMES, BIRD_COUNT,
                       PIG_COUNT, BLOCK_PIECES, BLOCK_SETS, SCENERY_CELLS,
                       CREATURE_W, CREATURE_H, BLOCK_W, BLOCK_H,
                       SCENERY_W, SCENERY_H)

BUILD = 'build'
STRIP_PX = 4                       # one CRTC char = 4 Mode 0 pixels
STRIP_BYTES = STRIP_PX // 2        # ...which is 2 nibble-packed bytes
STRIPS = SCENERY_W // STRIP_PX     # 8 strips across a scenery cell


def load(name):
    s = SHEETS[name]
    return artlib.sheet_read(s['path'], s['w'], s['h'], s['cols'], s['count'])


# ---------------------------------------------------------------------------
#  Straight nibble-packed bitmaps.
# ---------------------------------------------------------------------------
def pack_raw(cells, path):
    out = bytearray()
    for c in cells:
        out += artlib.pack_nibbles(c)
    open(os.path.join(BUILD, path), 'wb').write(out)
    return len(out)


# ---------------------------------------------------------------------------
#  Column-wise RLE for the scenery cells.
#
#  Stream per strip:  <count><b0><b1> repeated, counts summing to the cell
#  height. count is 1..255 so a full-height run of sky is three bytes.
#  The renderer never needs the length: it stops when it has emitted
#  SCENERY_H rows.
# ---------------------------------------------------------------------------
def rle_strip(cell, strip):
    rows = []
    for y in range(SCENERY_H):
        row = cell[y]
        x0 = strip * STRIP_PX
        rows.append(bytes(((row[x0] << 4) | row[x0 + 1],
                           (row[x0 + 2] << 4) | row[x0 + 3])))
    out = bytearray()
    i = 0
    while i < len(rows):
        n = 1
        while i + n < len(rows) and rows[i + n] == rows[i] and n < 255:
            n += 1
        out.append(n)
        out += rows[i]
        i += n
    return bytes(out)


def pack_scenery(cells):
    blobs, offsets, data = [], [], bytearray()
    for cell in cells:
        for s in range(STRIPS):
            blobs.append(rle_strip(cell, s))
    for b in blobs:
        offsets.append(len(data))
        data += b
    open(os.path.join(BUILD, 'scenery.raw'), 'wb').write(bytes(data))
    return offsets, len(data)


# ---------------------------------------------------------------------------
#  Equates: names for every frame, piece, set and scenery cell, plus the
#  per-material physics numbers the engine needs.
# ---------------------------------------------------------------------------
def write_defs(scen_offsets, sizes):
    """Two files, because the assembler needs them in different places:
    art_defs.inc is pure equates and is included BEFORE the org (hardware.inc
    is built on top of them), while art_tables.inc emits real bytes and has
    to land inside the code bank."""
    with open(os.path.join(BUILD, 'art_defs.inc'), 'w') as f:
        f.write('; AUTO-GENERATED by tools/gen_art.py — do not edit\n\n')

        f.write('; ---- creature frames -------------------------------\n')
        for i, n in enumerate(CREATURE_FRAMES):
            f.write('%-16s equ %d\n' % ('FR_' + n.upper(), i))
        f.write('%-16s equ %d\n' % ('FR_COUNT', len(CREATURE_FRAMES)))
        f.write('%-16s equ %d\n' % ('CR_FRAME_BYTES',
                                    CREATURE_W * CREATURE_H // 2))
        f.write('%-16s equ %d\n' % ('CR_BYTES_PER_ROW', CREATURE_W // 2))
        f.write('%-16s equ %d\n' % ('CR_HEIGHT', CREATURE_H))
        f.write('%-16s equ %d\n' % ('CR_WIDTH', CREATURE_W))
        f.write('%-16s equ %d\n' % ('BIRD_TYPES', BIRD_COUNT))
        f.write('%-16s equ %d\n' % ('PIG_TYPES', PIG_COUNT))
        for i, n in enumerate(CREATURE_NAMES[:BIRD_COUNT]):
            f.write('%-16s equ %d\n' % ('BIRD_' + n.upper(), i))
        for i, n in enumerate(CREATURE_NAMES[BIRD_COUNT:]):
            f.write('%-16s equ %d\n' % ('PIG_' + n.upper(), BIRD_COUNT + i))

        f.write('\n; ---- block pieces and material sets ----------------\n')
        for i, (n, _hp, _tall) in enumerate(BLOCK_PIECES):
            f.write('%-16s equ %d\n' % ('BLK_' + n.upper(), i))
        f.write('%-16s equ %d\n' % ('BLK_PIECES', len(BLOCK_PIECES)))
        for i, (n, _t, _p, _thin) in enumerate(BLOCK_SETS):
            f.write('%-16s equ %d\n' % ('SET_' + n.upper(), i))
        f.write('%-16s equ %d\n' % ('BLK_SETS', len(BLOCK_SETS)))
        f.write('%-16s equ %d\n' % ('BLK_BYTES', BLOCK_W * BLOCK_H // 2))
        f.write('%-16s equ %d\n' % ('BLK_BYTES_PER_ROW', BLOCK_W // 2))
        f.write('%-16s equ %d\n' % ('BLK_W', BLOCK_W))
        f.write('%-16s equ %d\n' % ('BLK_H', BLOCK_H))

        f.write('\n; ---- scenery --------------------------------------\n')
        for i, n in enumerate(SCENERY_CELLS):
            f.write('%-16s equ %d\n' % ('SC_' + n.upper(), i))
        f.write('%-16s equ %d\n' % ('SC_CELLS', len(SCENERY_CELLS)))
        f.write('%-16s equ %d\n' % ('SC_W', SCENERY_W))
        f.write('%-16s equ %d\n' % ('SC_H', SCENERY_H))
        f.write('%-16s equ %d\n' % ('SC_STRIPS', STRIPS))

        f.write('\n; ---- sizes (bytes) --------------------------------\n')
        for k, v in sizes.items():
            f.write('%-16s equ %d\n' % (k, v))

    with open(os.path.join(BUILD, 'art_tables.inc'), 'w') as f:
        f.write('; AUTO-GENERATED by tools/gen_art.py — do not edit\n')
        f.write('blk_hp_table:           ; [set][piece]\n')
        for _n, tough, _pens, _thin in BLOCK_SETS:
            vals = [max(1, min(255, hp * tough // 100))
                    for _p, hp, _tall in BLOCK_PIECES]
            f.write('        db      %s\n' % ','.join(str(v) for v in vals))
        f.write('\nblk_tall_table:         ; 1 = an upright, and it topples\n')
        f.write('        db      %s\n'
                % ','.join('1' if tall else '0'
                           for _p, _hp, tall in BLOCK_PIECES))
    #  The strip offsets go out as a BINARY. They are read-only and the code
    #  bank has no room: they ride down from video RAM with the creature
    #  art, like the font and the sine. See art.asm.
    blob = bytearray()
    for v in scen_offsets:
        blob += bytes((v & 0xFF, v >> 8))
    with open(os.path.join(BUILD, 'scenofs.raw'), 'wb') as f:
        f.write(bytes(blob))


def main():
    os.makedirs(BUILD, exist_ok=True)

    creatures = load('creatures')
    blocks = load('blocks')
    scenery = load('scenery')

    n_cre = pack_raw(creatures, 'creatures.raw')
    n_blk = pack_raw(blocks, 'blocks.raw')
    scen_ofs, n_scn = pack_scenery(scenery)

    sizes = {'CREATURE_ART_SIZE': n_cre,
             'BLOCK_ART_SIZE': n_blk,
             'SCENERY_RLE_SIZE': n_scn}
    write_defs(scen_ofs, sizes)

    raw_scn = len(scenery) * SCENERY_W * SCENERY_H // 2
    print('creatures.raw  %6d bytes  (%d frames)' % (n_cre, len(creatures)))
    print('blocks.raw     %6d bytes  (%d pieces)' % (n_blk, len(blocks)))
    print('scenery.raw    %6d bytes  (%d cells, %d raw — %.1f:1)'
          % (n_scn, len(scenery), raw_scn, raw_scn / float(n_scn)))


if __name__ == '__main__':
    main()
