#!/usr/bin/env python3
# ============================================================================
#  gen_rot.py — the tilt maps (stdout -> build/rot_tables.inc).
#
#  A beam that has lost the support under one end tips over the other, and
#  for that its pieces have to be drawn crooked. Rotating a 16x16 Mode 0
#  tile on a Z80 at 50 Hz is not on; storing four pre-tilted copies of all
#  fifty block sprites is 25 KB and there is no 25 KB.
#
#  So the GEOMETRY is computed here, once, as four 256-entry maps of
#  "destination pixel -> source pixel" (#FF meaning transparent). The
#  runtime applies a map to the ten pieces of whichever material set the
#  level uses, into 5 KB of RAM, at level load. One kilobyte of tables buys
#  tilted art for every piece, and the assembly never does trigonometry.
#
#  MODE 0 PIXELS ARE TWICE AS WIDE AS THEY ARE TALL, so the rotation is
#  done in PHYSICAL space — a 16x16 tile is a 32x16 rectangle on screen —
#  or the tilt comes out sheared instead of rotated.
#
#  The four angles are picked so the vertical drop per cell is a whole
#  number of scanlines: a cell is 32 physical units wide, so tan(t)*32 is
#  4 and 8 lines for the two magnitudes. That lets a long beam be drawn as
#  its own cells stepped down by a constant, which is what makes a
#  multi-cell plank tip as one rigid object.
# ============================================================================
import math

W = H = 16
SLOPES = [4, 8, -4, -8]          # scanlines of drop per cell, in tilt order

#  Equates go in their own file: state.inc sizes a RAM bank from ROT_TILTS
#  and is included before the org, while the tables themselves have to land
#  inside the code bank.
with open('build/rot_defs.inc', 'w') as f:
    f.write("; AUTO-GENERATED by tools/gen_rot.py — do not edit\n")
    f.write("%-16s equ %d\n" % ("ROT_TILTS", len(SLOPES)))
    f.write("%-16s equ %d\n" % ("TILT_NONE", 0))
    for i, sl in enumerate(SLOPES):
        f.write("%-16s equ %d\n"
                % ("TILT_%s%d" % ('D' if sl > 0 else 'U', abs(sl)), i + 1))

print("; AUTO-GENERATED by tools/gen_rot.py — do not edit, do not commit")
print("rot_slope:              ; scanlines per cell, tilt 0 = upright")
print("        db      0,%s" % ",".join(str(s & 0xFF) for s in SLOPES))

print("rot_map:")
for slope in SLOPES:
    theta = math.atan2(slope, 2 * W)          # cell is 2*W physical units wide
    ct, st = math.cos(theta), math.sin(theta)
    row = []
    for y in range(H):
        for x in range(W):
            u = 2 * (x + 0.5) - W             # physical, about the centre
            v = (y + 0.5) - H / 2.0
            us = u * ct + v * st              # inverse rotation
            vs = -u * st + v * ct
            sx = int(math.floor((us + W) / 2.0))
            sy = int(math.floor(vs + H / 2.0))
            row.append(sy * W + sx if 0 <= sx < W and 0 <= sy < H else 0xFF)
    print("        ; tilt %+d scanlines per cell (%.1f degrees)"
          % (slope, math.degrees(theta)))
    for i in range(0, len(row), 16):
        print("        db      " + ",".join("#%02X" % v for v in row[i:i + 16]))
