#!/usr/bin/env python3
# ============================================================================
#  music.py — compile assets/music.txt into steps the SOUND engine can play,
#  and export it back again.
#
#      python3 tools/music.py compile assets/music.txt build/
#      python3 tools/music.py export  build/music.raw   out.txt
#
#  There is no music player. A tune here is simply a very long sound in the
#  format sound.asm already reads — one step per note — so fifteen seconds
#  of title theme costs no code at all, only bytes. That is the whole trick,
#  and it is why the tune lives in the same six-byte step format as a pig's
#  squeal: one engine, two very different uses.
#
#  Melody and bass are separate sequences played on separate channels. They
#  are emitted back to back, and MUSIC_BASS_OFS says where the second one
#  starts.
#
#  Periods come from equal temperament, not a table anyone typed: the AY
#  tone period for a note is 125000/frequency, rounded.
# ============================================================================
import os
import sys

STEP = 6
NOISE_OFF = 0x40
SEMI = {'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11}


def period(name):
    """'A4' or 'F#3' -> the AY tone period. '-' is a rest."""
    if name == '-':
        return 0
    body, octave = name[:-1], int(name[-1])
    n = SEMI[body[0].upper()]
    if len(body) > 1:
        n += 1 if body[1] == '#' else -1
    midi = 12 * (octave + 1) + n
    freq = 440.0 * 2.0 ** ((midi - 69) / 12.0)
    p = int(round(125000.0 / freq))
    if not 1 <= p <= 4095:
        raise SystemExit('%s is outside the AY range (period %d)' % (name, p))
    return p


def parse(path):
    tempo, parts, cur = 9, {}, None
    for lineno, raw in enumerate(open(path), 1):
        line = raw.split('#')[0].strip()
        if not line:
            continue
        w = line.split()
        if w[0] == 'tempo':
            tempo = int(w[1])
        elif w[0] in ('melody', 'bass'):
            cur = parts.setdefault(w[0], [])
        elif cur is None:
            raise SystemExit('%s:%d: notes before any melody/bass' % (path, lineno))
        else:
            if len(w) % 2:
                raise SystemExit('%s:%d: notes come in NAME LENGTH pairs' % (path, lineno))
            for i in range(0, len(w), 2):
                cur.append((w[i], int(w[i + 1])))
    for k in ('melody', 'bass'):
        if k not in parts:
            raise SystemExit('%s: no %s' % (path, k))
    return tempo, parts


def emit(tempo, notes, vol, fade):
    blob, frames = bytearray(), 0
    for name, beats in notes:
        n = beats * tempo
        while n > 0:                      # a step's frame count is one byte
            d = min(n, 255)
            p = period(name)
            v = 0 if p == 0 else vol
            f = 0 if p == 0 else fade
            blob += bytes((d, p & 0xFF, (p >> 8) & 0x0F, 0,
                           (v & 0x0F) | (((f + 8) & 0x0F) << 4), NOISE_OFF))
            n -= d
        frames += beats * tempo
    blob.append(0)
    return bytes(blob), frames


def compile_(src, outdir):
    tempo, parts = parse(src)
    mel, mf = emit(tempo, parts['melody'], 13, -1)
    bas, bf = emit(tempo, parts['bass'], 9, 0)
    blob = mel + bas
    open(os.path.join(outdir, 'music.raw'), 'wb').write(blob)
    with open(os.path.join(outdir, 'music_defs.inc'), 'w') as f:
        f.write('; generated by tools/music.py — do not edit\n')
        f.write('MUSIC_SIZE       equ %d\n' % len(blob))
        f.write('MUSIC_BASS_OFS   equ %d\n' % len(mel))
    print('%s: melody %d frames (%.1f s), bass %d frames (%.1f s), %d bytes'
          % (src, mf, mf / 50.0, bf, bf / 50.0, len(blob)))


def export(rawpath, outpath):
    blob = open(rawpath, 'rb').read()
    #  Periods back to the nearest note name, so the export is readable
    #  rather than a wall of numbers.
    names = {}
    for octave in range(1, 8):
        for b in SEMI:
            for acc in ('', '#'):
                try:
                    names[period(b + acc + str(octave))] = b + acc + str(octave)
                except SystemExit:
                    pass
    out, i, part = [], 0, []
    while i < len(blob):
        if blob[i] == 0:
            out.append(part); part = []; i += 1; continue
        d, plo, phi = blob[i], blob[i + 1], blob[i + 2]
        p = plo | (phi << 8)
        part.append((names.get(p, '-') if p else '-', d))
        i += STEP
    with open(outpath, 'w') as f:
        f.write('# exported by tools/music.py from %s\n'
                '# lengths are in FRAMES here, not beats\n'
                'tempo 1\n' % os.path.basename(rawpath))
        for name, seq in zip(('melody', 'bass'), out):
            f.write('\n%s\n' % name)
            for j in range(0, len(seq), 8):
                f.write('  ' + '  '.join('%s %d' % s for s in seq[j:j + 8]) + '\n')
    print('%s -> %s' % (rawpath, outpath))


if __name__ == '__main__':
    if len(sys.argv) == 4 and sys.argv[1] == 'compile':
        compile_(sys.argv[2], sys.argv[3])
    elif len(sys.argv) == 4 and sys.argv[1] == 'export':
        export(sys.argv[2], sys.argv[3])
    else:
        raise SystemExit('usage: music.py compile|export IN OUT')
