#!/usr/bin/env python3
# ============================================================================
#  sounds.py — compile assets/sounds.txt into the binary the player reads,
#  and export it back again.
#
#      python3 tools/sounds.py compile assets/sounds.txt build/
#      python3 tools/sounds.py export  build/sounds.raw  assets/sounds.txt
#
#  The export is not a convenience, it is the point: every asset in this
#  game has a round trip, so the text file is the source of truth and can
#  always be rebuilt from what actually shipped. Compile then export and you
#  get the file you started with, modulo comments.
#
#  A step is SIX bytes, laid out so the Z80 player can walk it with plain
#  increments and no arithmetic:
#
#      0  frames
#      1  period low
#      2  period high
#      3  slide      (signed, added to the period each frame)
#      4  volume     (low nibble) | vfade+8 (high nibble)
#      5  noise      (0..31 period, +32 = tone off, +64 = noise off)
#
#  A sound ends with a zero frame count. Byte 5's "noise off" bit is set by
#  the compiler when noise is 0, so the player never has to test for it.
# ============================================================================
import os
import re
import sys

STEP = 6
NOISE_OFF = 0x40
TONE_OFF = 0x20


def parse(path):
    sounds, cur = [], None
    for lineno, raw in enumerate(open(path), 1):
        line = raw.split('#')[0].strip()
        if not line:
            continue
        parts = line.split()
        if parts[0] == 'sound':
            if len(parts) != 2:
                raise SystemExit('%s:%d: sound needs exactly a name' % (path, lineno))
            cur = (parts[1], [])
            sounds.append(cur)
        elif parts[0] == 'step':
            if cur is None:
                raise SystemExit('%s:%d: step before any sound' % (path, lineno))
            if len(parts) != 7:
                raise SystemExit('%s:%d: step needs 6 numbers, got %d'
                                 % (path, lineno, len(parts) - 1))
            frames, period, slide, vol, vfade, noise = (int(x) for x in parts[1:])
            for name, v, lo, hi in (('frames', frames, 1, 255),
                                    ('period', period, 0, 4095),
                                    ('slide', slide, -128, 127),
                                    ('vol', vol, 0, 15),
                                    ('vfade', vfade, -8, 7),
                                    ('noise', noise, 0, 63)):
                if not lo <= v <= hi:
                    raise SystemExit('%s:%d: %s must be %d..%d, got %d'
                                     % (path, lineno, name, lo, hi, v))
            cur[1].append((frames, period, slide, vol, vfade, noise))
        else:
            raise SystemExit('%s:%d: expected "sound" or "step", got %r'
                             % (path, lineno, parts[0]))
    if not sounds:
        raise SystemExit('%s: no sounds' % path)
    for name, steps in sounds:
        if not steps:
            raise SystemExit('%s: sound %s has no steps' % (path, name))
    return sounds


def emit(sounds):
    blob, offsets = bytearray(), []
    for name, steps in sounds:
        offsets.append((name, len(blob)))
        for frames, period, slide, vol, vfade, noise in steps:
            ctl = noise & 0x3F
            if (noise & 0x1F) == 0 and noise < 32:
                ctl |= NOISE_OFF            # pure tone: leave the noise out
            blob += bytes((frames,
                           period & 0xFF, (period >> 8) & 0x0F,
                           slide & 0xFF,
                           (vol & 0x0F) | (((vfade + 8) & 0x0F) << 4),
                           ctl))
        blob.append(0)                      # end of sound
    #  The lookup table rides along at the end, so it costs the code bank
    #  nothing either. The player finds it at SOUND_OFS.
    table = len(blob)
    for _, off in offsets:
        blob += bytes((off & 0xFF, off >> 8))
    return bytes(blob), offsets, table


def compile_(src, outdir):
    sounds = parse(src)
    blob, offsets, table = emit(sounds)
    open(os.path.join(outdir, 'sounds.raw'), 'wb').write(blob)
    with open(os.path.join(outdir, 'sound_defs.inc'), 'w') as f:
        f.write('; generated by tools/sounds.py — do not edit\n')
        f.write('SND_COUNT        equ %d\n' % len(offsets))
        f.write('SOUNDS_SIZE      equ %d\n' % len(blob))
        f.write('SOUND_OFS        equ SOUNDS_BASE+%d\n' % table)
        for i, (name, _) in enumerate(offsets):
            f.write('SND_%-14s equ %d\n' % (name.upper(), i))
    print('%s: %d sounds, %d bytes' % (src, len(offsets), len(blob)))


def export(rawpath, outpath):
    blob = open(rawpath, 'rb').read()
    #  Offsets are not in the blob, so recover the boundaries the same way
    #  the player does: a sound runs until a zero frame count.
    sounds, i, n = [], 0, 0
    while i < len(blob) and blob[i]:
        steps = []
        while blob[i]:
            frames, plo, phi, slide, volb, ctl = blob[i:i + STEP]
            steps.append((frames, plo | (phi << 8),
                          slide - 256 if slide > 127 else slide,
                          volb & 0x0F, ((volb >> 4) & 0x0F) - 8,
                          0 if ctl & NOISE_OFF else ctl & 0x3F))
            i += STEP
        i += 1
        sounds.append(('sound%02d' % n, steps))
        n += 1
    with open(outpath, 'w') as f:
        f.write('# exported by tools/sounds.py from %s\n'
                '# see the original assets/sounds.txt for what the columns mean\n\n'
                % os.path.basename(rawpath))
        for name, steps in sounds:
            f.write('sound %s\n' % name)
            for s in steps:
                f.write('  step %3d %4d %4d %3d %3d %3d\n' % s)
            f.write('\n')
    print('%s -> %s (%d sounds)' % (rawpath, outpath, len(sounds)))


if __name__ == '__main__':
    if len(sys.argv) == 4 and sys.argv[1] == 'compile':
        compile_(sys.argv[2], sys.argv[3])
    elif len(sys.argv) == 4 and sys.argv[1] == 'export':
        export(sys.argv[2], sys.argv[3])
    else:
        raise SystemExit(__doc__ or 'usage: sounds.py compile|export IN OUT')
